name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release Pipeline"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
